### PR TITLE
Remove incorrect block index sections from asdf test data

### PR DESCRIPTION
**Pull request by braingram**
Asdf is making some major updates to internal block reading and writing code (see [this PR](https://github.com/asdf-format/asdf/pull/1537) for the extensive changes).

One of the changes includes issuing a new warning when a file is opened which contains an incorrect block index. The block index is a small, optional YAML document at the end of an ASDF file that contains the offsets of each ASDF binary block within the ASDF file (see the [asdf-standard docs](https://asdf-standard.readthedocs.io/en/1.0.3/file_layout.html#block-index) for more details). Hand editing ASDF files can often lead to incorrect offsets in the block index. When asdf detects a block index that is incorrect (or if no block index is found) it ignores the block index and falls back to reading blocks sequentially starting with the first.

With dkist main tested against the above asdf PR several tests are failing (see [here for the full log](https://github.com/asdf-format/asdf/actions/runs/5859350013/job/15885164575?pr=1537#step:10:3336)):
```
=========================== short test summary info ============================
FAILED dkist/dkist/io/asdf/tests/test_dataset.py::test_read_all_schema_versions[eit_dataset_asdf_path0]
FAILED dkist/dkist/io/asdf/tests/test_dataset.py::test_read_all_schema_versions[eit_dataset_asdf_path1]
FAILED dkist/dkist/io/asdf/tests/test_dataset.py::test_read_all_schema_versions[eit_dataset_asdf_path2]
FAILED dkist/dkist/io/asdf/tests/test_dataset.py::test_read_all_schema_versions[eit_dataset_asdf_path3]
FAILED dkist/dkist/io/asdf/tests/test_dataset.py::test_loader_getitem_with_chunksize[eit_dataset_asdf_path0]
FAILED dkist/dkist/io/asdf/tests/test_dataset.py::test_loader_getitem_with_chunksize[eit_dataset_asdf_path1]
FAILED dkist/dkist/io/asdf/tests/test_dataset.py::test_loader_getitem_with_chunksize[eit_dataset_asdf_path2]
FAILED dkist/dkist/io/asdf/tests/test_dataset.py::test_loader_getitem_with_chunksize[eit_dataset_asdf_path3]
ERROR dkist/dkist/io/tests/test_file_manager.py::test_length_one_first_array_axis
ERROR dkist/dkist/io/tests/test_file_manager.py::test_download_quality[kwargs0]
ERROR dkist/dkist/io/tests/test_file_manager.py::test_download_quality[kwargs1]
ERROR dkist/dkist/io/tests/test_file_manager.py::test_download_quality_movie[kwargs0]
ERROR dkist/dkist/io/tests/test_file_manager.py::test_download_quality_movie[kwargs1]
======== 8 failed, 286 passed, 2 skipped, 5 errors in 138.79s (0:02:18) ========
```

This is due to several test files in the dkist repository that contain block index offsets that are incorrect (see the changed files in this PR).

This PR deletes the invalid block index from each of these files.

### CODE REVIEW

**Comment by braingram** [comment]
I wasn't sure if these changes warranted a changelog. I'm unable to change labels (if there is one that allows `no-changelog-entry` or similar).

**Comment by Cadair** [comment]
I don't know if it's related to this PR yet or not, but I just tried to write a test which makes use of the WCSes in these files and it's now causing segfaults, which is fun. @braingram got any ideas? :laughing:

**Comment by Cadair** [comment]
yeah if I revert this PR (and install asdf<3) then I don't get the segfaults.

**Comment by Cadair** [comment]
Without this PR the 1.0.0 eit_dataset file does not segfault the others do. with this PR 1.0.0 does as well but not 1.1.0 (which wasn't modified in this PR).

**Comment by braingram** [comment]
Would you point me to the test?

Using asdf main and dkist main and `dkist/data/test/eit_dataset-1.0.0.asdf`, if I open the asdf file, take a reference to the wcs, then close the asdf file and access the wcs I do get a segfault.
```python
af = asdf.open('dkist/data/test/eit_dataset-1.0.0.asdf')
w = af['dataset'].wcs
af.close()
print(w)  # segfault
```
Keeping the file open (which by default is being memory mapped) prevents the segfault. Also, passing `copy_arrays=True` to `asdf.open` also prevents the segfault (as the arrays contained in the wcs are no longer memory mapped). I see the same behavior with asdf 2.15.2. However I am also seeing the same behavior after reverting 1529024168fc139e62ffc5efeec2e3be1636ca07 so I don't think I'm testing the same thing you are based on your description of the issue.

**Pull request merged**
