### PR TITLE
Pin dask to <2024.12.0 to avoid performance regression

### PR DESCRIPTION
**Pull request by SolarDrew**

### CODE REVIEW

**Comment by SolarDrew** [comment]
Yeah that's fair. I'm not sure we want to take the performance hit either though, it's not small.

**Comment by Cadair** [comment]
Yeah, we should debug it further and figure it out. This seem to have not fixed it anyway?

**Comment by SolarDrew** [comment]
Presumably that's because it's running the unpinned version as it exists on main?

**Comment by SolarDrew** [comment]
Closing until we've figured out what is actually happening.

**Pull request closed without merging**
